### ISSUE TITLE
Any plans to add another user category, superuser (admin was taken lol)?

### ISSUE THREAD

**Issue by 0xecho** [frectonz/trantor#3]
Currently anyone can "invite" themselves to the platform, there is no proper authorization scheme. No way for someone hosting this thing to control what is happening.
Case in point I created a new user by just sending a POST

**Comment by frectonz** [comment]
Thanks for taking an interest in the proect, and yeah you're right anyone can "invite" themselves to the platform that's by design and is documented on the README. 

The user creation route was only meant for the demo server it will be removed after some time. You should think of it as just "registering". 

I am currently implementing a user management system in which you can configure a default user via the `config.toml` file and only that user can create other users.

I saw the `secret_code` you used to create the user, nicely played 👏 😂

**Comment by 0xecho** [comment]
Awesome :ok_hand:  good to know its on the roadmap. super excited to see where this goes :bangbang: :bangbang:
